/** Declaration file generated by dts-gen */

export function clearAllBodyScrollLocks(): void;

export function disableBodyScroll(r: any, o: any): any;

export function enableBodyScroll(e: any): any;

export namespace clearAllBodyScrollLocks {
    const prototype: {
    };

}

export namespace disableBodyScroll {
    const prototype: {
    };

}

export namespace enableBodyScroll {
    const prototype: {
    };

}

